export const STORAGE_KEYS = {
  ACTIVE_SESSION_LOCK: 'qum_active_session_lock',
  TASK_CACHE: 'qum_task_cache',
  SYNC_QUEUE: 'qum_sync_queue',
  PENDING_RAGE_QUIT: 'qum_pending_rage_quit',
  NOTIFICATION_SCHEDULE: 'qum_notification_schedule',
  PROFILE_CACHE: 'qum_profile_cache',
  CRASH_REPORTS_OUTBOX: 'qum_crash_reports_outbox',
  REFLECTIONS_OUTBOX: 'qum_reflections_outbox',
  REFLECTION_SCHEDULE: 'qum_reflection_schedule',
  COMMITMENTS_CACHE: 'qum_commitments_cache',
  COMMITMENT_HONORED_CELEBRATED: 'qum_commitment_honored_celebrated',
  LETTER_CACHE: 'qum_letter_cache',
  LETTER_STARTERS_DISMISSED: 'qum_letter_starters_dismissed',
  LETTER_STARTER_PICK_COUNT: 'qum_letter_starter_pick_count',
  VOICE_MEMO_CACHE: 'qum_voice_memo_cache',
  CALM_HOUR_SCHEDULE: 'qum_calm_hour_schedule',
  CALM_HOUR_PREFS: 'qum_calm_hour_prefs',
  CALM_HOUR_CARD_DISMISS: 'qum_calm_hour_card_dismiss',
  SOLIDARITY_CACHE: 'qum_solidarity_cache',
  CRISIS_CARD_DISMISS: 'qum_crisis_card_dismiss',
  HAPTICS_ENABLED: 'qum_haptics_enabled',
} as const;
